### ISSUE TITLE
ModuleNotFoundError: No module named 'functions'

### ISSUE THREAD

**Issue by suyanpengzhang** [benmiroglio/pymatch#2]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-20-0149f742cb36> in <module>()
----> 1 from pymatch.Matcher import Matcher

~/anaconda3/lib/python3.6/site-packages/pymatch/__init__.py in <module>()
      6 from collections import Counter
      7 from itertools import chain
----> 8 import functions as uf
      9 import statsmodels.api as sm
     10 import patsy

ModuleNotFoundError: No module named 'functions'

**Comment by Cojabi** [comment]
@benmiroglio same for me installing it via pip3

**Comment by benmiroglio** [comment]
@Cojabi can you verify the updated version fixes this issue?

**Comment by abedkhooli** [comment]
Apparently, it doesn't work in Python 3.6 as it assumes 'functions' an installed package. pymatch V 0.3
To run "from pymatch.Matcher import Matcher" successfully (did not run any code yet), I adjusted the local imports:
from . import functions as uf (in init and matcher)
indented line 345 (var_order = [ ....) as it doesn't look correct (got error in the return statement in line 357).
This may not work with earlier versions of Python! Sorry, not an expert to provide a PR.

**Comment by abedkhooli** [comment]
In addition to the 2 imports, there is a potential issue in [compare_continuous](https://github.com/benmiroglio/pymatch/blob/e4961e6ec134439fc519a24333a62c77ac526e7f/pymatch/Matcher.py#L254). After fixing indentation (now fixed in source), cell 20 in this [notebook example](https://github.com/benmiroglio/pymatch/blob/master/Example.ipynb) generates an error: 
ValueError: zero-dimensional arrays cannot be concatenated 
starts [Line 305](url)https://github.com/benmiroglio/pymatch/blob/master/pymatch/Matcher.py#L305 -> calls [functions 78](https://github.com/benmiroglio/pymatch/blob/master/pymatch/functions.py#L78) -> 54 -> 41 then numpy concatenate: return unique(np.concatenate((ar1, ar2))) 
This may only apply to latest Python 3.x versions.

**Comment by benmiroglio** [comment]
@Cojabi's PR and a few other tweaks allow me to run the full example notebook on python2 and python3.6. Please update the package (0.3.3) and test to see if any errors persist.

**Comment by abedkhooli** [comment]
Passed (slowly but surely - for the compare_continuous function). Using Python 3.6.4
Thanks to all.

**Comment by iriosu** [comment]
Hi,
I just installed the last version of pymatch (0.3.3) on Python 3.6.2 and I'm getting the same error: "module 'pymatch' has no attribute 'functions'"
Any suggestions?

**Comment by abedkhooli** [comment]
May be you have different environments (different copies of pymatch). Best is to compare your pymtach files with https://github.com/benmiroglio/pymatch/tree/master/pymatch
